
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgb(ff9d00) rgb(dd00ff) 45deg
    col.inactive_border = rgba(595959aa)

    layout = master

    allow_tearing = false
}

xwayland {
    force_zero_scaling = true
}

