preload = ~/Dropbox/wallpaper1.jpg
splash = false
wallpaper = HDMI-A-1,~/Dropbox/wallpaper1.jpg
wallpaper = eDP-1,~/Dropbox/wallpaper1.jpg
wallpaper = eDP-2,~/Dropbox/wallpaper1.jpg
wallpaper = HDMI-A-2,~/Dropbox/wallpaper1.jpg
wallpaper = DP-1,~/Dropbox/wallpaper1.jpg
wallpaper = DP-2,~/Dropbox/wallpaper1.jpg
wallpaper = DP-3,~/Dropbox/wallpaper1.jpg
wallpaper = DP-10,~/Dropbox/wallpaper1.jpg
wallpaper = DP-11,~/Dropbox/wallpaper1.jpg
