preload = $HOME/.config/hypr/wallpapers/wallpaper1.jpg
# Disable the Hyprland splash logo on wallpaper
splash = false

# Enable IPC for dynamic wallpaper changes
ipc = true

# Set wallpaper
wallpaper {
    monitor =
    path = $HOME/.config/hypr/wallpapers/wallpaper1.jpg
    fit_mode = cover
}

