preload = ~/Dropbox/wallpaper1.jpg
# Disable the Hyprland splash logo on wallpaper
splash = false

# Enable IPC for dynamic wallpaper changes
ipc = true

# Set your wallpaper
wallpaper {
    monitor =
    path = ~/Dropbox/wallpaper1.jpg
    fit_mode = cover
}

