
dwindle {
    pseudotile = true
    preserve_split = true
    smart_split = false
    smart_resizing = true
}

master {
    new_status = master
    mfact = 0.5
    orientation = left
#    always_center_master = false
}

group {
    col.border_active = rgb(ff9d00)
    col.border_inactive = rgba(595959aa)

    groupbar {
        font_size = 10
        gradients = true
        render_titles = true
        scrolling = true
    }
}

