
windowrule = match:class ^(.*Vivaldi.*)$, tile on
windowrule = match:class ^(.*pavucontrol.*)$, float on
windowrule = match:class ^(.*nm-connection-editor.*)$, float on
windowrule = match:class ^(.*vlc.*)$, no_anim on
windowrule = match:class ^(.*smplayer.*)$, no_anim on
windowrule = match:class ^(.*python3.*)$, float on

windowrule = match:class ^(.*yad.*)$, float on
windowrule = match:class ^(.*yad.*)$, move 2% 2%
windowrule = match:class ^(.*yad.*)$, size 96% 96%
windowrule = match:class ^(.*steam_app_489830.*)$, float on
windowrule = match:class ^(.*steam_app_489830.*)$, move 2% 2%
windowrule = match:class ^(.*steam_app_489830.*)$, size 96% 96%

windowrule = match:class ^(.*terminator.*)$, workspace 1
windowrule = match:class ^(.*alacritty.*)$, workspace 1
windowrule = match:class ^(.*kitty.*)$, workspace 1
windowrule = match:class ^(.*[Vv]ivaldi.*)$, workspace 2
windowrule = match:class ^(.*[Ff]irefox.*)$, workspace 2
windowrule = match:class ^(.*[Ll]ibrewolf.*)$, workspace 2
windowrule = match:class ^(.*subl.*)$, workspace 3
windowrule = match:class ^(.*[Vv][Ss][Cc]odium.*)$, workspace 3
windowrule = match:class ^(.*thunar.*)$, workspace 4
windowrule = match:class ^(.*Signal.*)$, workspace 5
windowrule = match:class ^(.*[Dd]iscord.*)$, workspace 5
windowrule = match:class ^(.*Microsoft Teams.*)$, workspace 5
windowrule = match:class ^(.*thunderbird.*)$, workspace 6
windowrule = match:class ^(.*vlc.*)$, workspace 7
windowrule = match:class ^(.*smplayer.*)$, workspace 7
windowrule = match:class ^(.*FreeTube.*)$, workspace 7
windowrule = match:class ^(.*[Ss]team.*)$, workspace 8
windowrule = match:class ^(.*[Hh]eroic.*)$, workspace 8
windowrule = match:class ^(.*yad.*)$, workspace 8
windowrule = match:class ^(.*gdlauncher.*)$, workspace 8
windowrule = match:class ^(.*polymc.*)$, workspace 8
windowrule = match:class ^(.*org.multimc.MultiMC.*)$, workspace 8
windowrule = match:class ^(.*org.prismlauncher.PrismLauncher.*)$, workspace 8
windowrule = match:class ^(.*factorio.*)$, workspace 9
windowrule = match:class ^(.*Better MC.*)$, workspace 9
windowrule = match:class ^(.*Minecraft.*)$, workspace 9
windowrule = match:class ^(.*FTB Skies.*)$, workspace 9
windowrule = match:class ^(.*UniversIO.*)$, workspace 9
windowrule = match:class ^(.*Stone Technology.*)$, workspace 9
windowrule = match:class ^(.*Enigmatica.*)$, workspace 9
windowrule = match:class ^(.*SteamPunk.*)$, workspace 9
windowrule = match:class ^(.*Another Quality.*)$, workspace 9
windowrule = match:class ^(.*steam_app_.*)$, workspace 9
windowrule = match:class ^(.*erraria.*)$, workspace 9
windowrule = match:class ^(.*[Vv]irtual[Bb]ox.*)$, workspace 10
windowrule = match:class ^(com\.obsproject\.Studio)$, workspace 11
windowrule = match:class ^(.*sublime_merge.*)$, workspace 12
windowrule = match:class ^(.*q[Bb]ittorrent.*)$, workspace 13

windowrule = match:title ^(Open)$, float on
windowrule = match:title ^(Choose Files)$, float on
windowrule = match:title ^(Save As)$, float on
windowrule = match:title ^(Confirm to replace files)$, float on
windowrule = match:title ^(File Operation Progress)$, float on

workspace = special:magic, gapsout:50, gapsin:20
