
windowrulev2 = tile, class:^(.*Vivaldi.*)$
windowrulev2 = float, class:^(.*pavucontrol.*)$
windowrulev2 = float, class:^(.*nm-connection-editor.*)$
windowrulev2 = noanim, class:^(.*vlc.*)$
windowrulev2 = noanim, class:^(.*smplayer.*)$
windowrulev2 = float, class:^(.*python3.*)$

windowrulev2 = float, class:^(.*yad.*)$
windowrulev2 = move 2% 2%, class:^(.*yad.*)$
windowrulev2 = size 96% 96%, class:^(.*yad.*)$
windowrulev2 = float, class:^(.*steam_app_489830.*)$
windowrulev2 = move 2% 2%, class:^(.*steam_app_489830.*)$
windowrulev2 = size 96% 96%, class:^(.*steam_app_489830.*)$

windowrulev2 = workspace 1, class:^(.*terminator.*)$
windowrulev2 = workspace 2, class:^(.*[Vv]ivaldi.*)$
windowrulev2 = workspace 2, class:^(.*[Ff]irefox.*)$
windowrulev2 = workspace 3, class:^(.*subl.*)$
windowrulev2 = workspace 3, class:^(.*[Vv][Ss][Cc]odium.*)$
windowrulev2 = workspace 4, class:^(.*thunar.*)$
windowrulev2 = workspace 5, class:^(.*Signal.*)$
windowrulev2 = workspace 5, class:^(.*[Dd]iscord.*)$
windowrulev2 = workspace 5, class:^(.*Microsoft Teams.*)$
windowrulev2 = workspace 6, class:^(.*thunderbird.*)$
windowrulev2 = workspace 7, class:^(.*vlc.*)$
windowrulev2 = workspace 7, class:^(.*smplayer.*)$
windowrulev2 = workspace 7, class:^(.*FreeTube.*)$
windowrulev2 = workspace 8, class:^(.*[Ss]team.*)$
windowrulev2 = workspace 8, class:^(.*[Hh]eroic.*)$
windowrulev2 = workspace 8, class:^(.*yad.*)$
windowrulev2 = workspace 8, class:^(.*gdlauncher.*)$
windowrulev2 = workspace 8, class:^(.*polymc.*)$
windowrulev2 = workspace 8, class:^(.*org.multimc.MultiMC.*)$
windowrulev2 = workspace 8, class:^(.*org.prismlauncher.PrismLauncher.*)$
windowrulev2 = workspace 9, class:^(.*factorio.*)$
windowrulev2 = workspace 9, class:^(.*Better MC.*)$
windowrulev2 = workspace 9, class:^(.*Minecraft.*)$
windowrulev2 = workspace 9, class:^(.*FTB Skies.*)$
windowrulev2 = workspace 9, class:^(.*UniversIO.*)$
windowrulev2 = workspace 9, class:^(.*Stone Technology.*)$
windowrulev2 = workspace 9, class:^(.*Enigmatica.*)$
windowrulev2 = workspace 9, class:^(.*SteamPunk.*)$
windowrulev2 = workspace 9, class:^(.*Another Quality.*)$
windowrulev2 = workspace 9, class:^(.*steam_app_.*)$
windowrulev2 = workspace 9, class:^(.*erraria.*)$
windowrulev2 = workspace 10, class:^(.*[Vv]irtual[Bb]ox.*)$
windowrulev2 = workspace 11, class:^(com\.obsproject\.Studio)$
windowrulev2 = workspace 12, class:^(.*sublime_merge.*)
windowrulev2 = workspace 13, class:^(.*q[Bb]ittorrent.*)

windowrule = float, title:^(Open)$
windowrule = float, title:^(Choose Files)$
windowrule = float, title:^(Save As)$
windowrule = float, title:^(Confirm to replace files)$
windowrule = float, title:^(File Operation Progress)$

workspace = special:magic, gapsout:50, gapsin:20
