
windowrule = tile on, match:class ^(.*Vivaldi.*)$
windowrule = float on, match:class ^(.*pavucontrol.*)$
windowrule = float on, match:class ^(.*nm-connection-editor.*)$
windowrule = no_anim on, match:class ^(.*vlc.*)$
windowrule = no_anim on, match:class ^(.*smplayer.*)$
windowrule = float on, match:class ^(.*python3.*)$

windowrule = float on, match:class ^(.*yad.*)$
windowrule = move 2% 2%, match:class ^(.*yad.*)$
windowrule = size 96% 96%, match:class ^(.*yad.*)$
windowrule = float on, match:class ^(.*steam_app_489830.*)$
windowrule = move 2% 2%, match:class ^(.*steam_app_489830.*)$
windowrule = size 96% 96%, match:class ^(.*steam_app_489830.*)$

windowrule = workspace 1, match:class ^(.*terminator.*)$
windowrule = workspace 2, match:class ^(.*[Vv]ivaldi.*)$
windowrule = workspace 2, match:class ^(.*[Ff]irefox.*)$
windowrule = workspace 3, match:class ^(.*subl.*)$
windowrule = workspace 3, match:class ^(.*[Vv][Ss][Cc]odium.*)$
windowrule = workspace 4, match:class ^(.*thunar.*)$
windowrule = workspace 5, match:class ^(.*Signal.*)$
windowrule = workspace 5, match:class ^(.*[Dd]iscord.*)$
windowrule = workspace 5, match:class ^(.*Microsoft Teams.*)$
windowrule = workspace 6, match:class ^(.*thunderbird.*)$
windowrule = workspace 7, match:class ^(.*vlc.*)$
windowrule = workspace 7, match:class ^(.*smplayer.*)$
windowrule = workspace 7, match:class ^(.*FreeTube.*)$
windowrule = workspace 8, match:class ^(.*[Ss]team.*)$
windowrule = workspace 8, match:class ^(.*[Hh]eroic.*)$
windowrule = workspace 8, match:class ^(.*yad.*)$
windowrule = workspace 8, match:class ^(.*gdlauncher.*)$
windowrule = workspace 8, match:class ^(.*polymc.*)$
windowrule = workspace 8, match:class ^(.*org.multimc.MultiMC.*)$
windowrule = workspace 8, match:class ^(.*org.prismlauncher.PrismLauncher.*)$
windowrule = workspace 9, match:class ^(.*factorio.*)$
windowrule = workspace 9, match:class ^(.*Better MC.*)$
windowrule = workspace 9, match:class ^(.*Minecraft.*)$
windowrule = workspace 9, match:class ^(.*FTB Skies.*)$
windowrule = workspace 9, match:class ^(.*UniversIO.*)$
windowrule = workspace 9, match:class ^(.*Stone Technology.*)$
windowrule = workspace 9, match:class ^(.*Enigmatica.*)$
windowrule = workspace 9, match:class ^(.*SteamPunk.*)$
windowrule = workspace 9, match:class ^(.*Another Quality.*)$
windowrule = workspace 9, match:class ^(.*steam_app_.*)$
windowrule = workspace 9, match:class ^(.*erraria.*)$
windowrule = workspace 10, match:class ^(.*[Vv]irtual[Bb]ox.*)$
windowrule = workspace 11, match:class ^(com\.obsproject\.Studio)$
windowrule = workspace 12, match:class ^(.*sublime_merge.*)$
windowrule = workspace 13, match:class ^(.*q[Bb]ittorrent.*)$

windowrule = float on, match:title ^(Open)$
windowrule = float on, match:title ^(Choose Files)$
windowrule = float on, match:title ^(Save As)$
windowrule = float on, match:title ^(Confirm to replace files)$
windowrule = float on, match:title ^(File Operation Progress)$

workspace = special:magic, gapsout:50, gapsin:20

